// Auto-generated by generate-vad-asr.py. DO NOT EDIT.

use std::path::Path;

use sherpa_onnx::{
    OfflineCanaryModelConfig, OfflineDolphinModelConfig,
    OfflineFireRedAsrCtcModelConfig, OfflineFireRedAsrModelConfig,
    OfflineFunASRNanoModelConfig, OfflineMedAsrCtcModelConfig,
    OfflineMoonshineModelConfig, OfflineNemoEncDecCtcModelConfig,
    OfflineOmnilingualAsrCtcModelConfig, OfflineParaformerModelConfig,
    OfflineQwen3ASRModelConfig, OfflineRecognizerConfig,
    OfflineSenseVoiceModelConfig, OfflineTransducerModelConfig,
    OfflineWenetCtcModelConfig, OfflineWhisperModelConfig,
    OfflineZipformerCtcModelConfig,
};

pub fn get_model_config(model_type: u32, model_dir: &Path) -> Option<OfflineRecognizerConfig> {
    let p = |sub: &str| -> Option<String> {
        let path = model_dir.join(sub);
        if !path.exists() { return None; }
        Some(path.to_str()?.to_string())
    };
    match model_type {
        0 => {
            // sherpa-onnx-paraformer-zh-2023-09-14
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.paraformer = OfflineParaformerModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("paraformer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            config.rule_fsts = p("itn_zh_number.fst");
            Some(config)
        }

        1 => {
            // icefall-asr-multidataset-pruned_transducer_stateless7-2023-05-04
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder-epoch-30-avg-4.int8.onnx"),
                decoder: p("decoder-epoch-30-avg-4.onnx"),
                joiner: p("joiner-epoch-30-avg-4.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        2 => {
            // sherpa-onnx-whisper-tiny.en
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.whisper = OfflineWhisperModelConfig {
                encoder: p("tiny.en-encoder.int8.onnx"),
                decoder: p("tiny.en-decoder.int8.onnx"),
                language: Some("en".into()),
                task: Some("transcribe".into()),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("whisper".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        3 => {
            // sherpa-onnx-whisper-base.en
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.whisper = OfflineWhisperModelConfig {
                encoder: p("base.en-encoder.int8.onnx"),
                decoder: p("base.en-decoder.int8.onnx"),
                language: Some("en".into()),
                task: Some("transcribe".into()),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("whisper".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        4 => {
            // icefall-asr-zipformer-wenetspeech-20230615
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder-epoch-12-avg-4.int8.onnx"),
                decoder: p("decoder-epoch-12-avg-4.onnx"),
                joiner: p("joiner-epoch-12-avg-4.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        5 => {
            // sherpa-onnx-zipformer-multi-zh-hans-2023-9-2
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder-epoch-20-avg-1.int8.onnx"),
                decoder: p("decoder-epoch-20-avg-1.onnx"),
                joiner: p("joiner-epoch-20-avg-1.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        6 => {
            // sherpa-onnx-nemo-ctc-en-citrinet-512
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        7 => {
            // sherpa-onnx-nemo-fast-conformer-ctc-be-de-en-es-fr-hr-it-pl-ru-uk-20k
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        8 => {
            // sherpa-onnx-nemo-fast-conformer-ctc-en-24500
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        9 => {
            // sherpa-onnx-nemo-fast-conformer-ctc-en-de-es-fr-14288
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        10 => {
            // sherpa-onnx-nemo-fast-conformer-ctc-es-1424
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        11 => {
            // sherpa-onnx-telespeech-ctc-int8-zh-2024-06-04
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.telespeech_ctc = p("model.int8.onnx");
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("telespeech_ctc".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        12 => {
            // sherpa-onnx-zipformer-thai-2024-06-20
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder-epoch-12-avg-5.int8.onnx"),
                decoder: p("decoder-epoch-12-avg-5.onnx"),
                joiner: p("joiner-epoch-12-avg-5.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        13 => {
            // sherpa-onnx-zipformer-korean-2024-06-24
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder-epoch-99-avg-1.int8.onnx"),
                decoder: p("decoder-epoch-99-avg-1.onnx"),
                joiner: p("joiner-epoch-99-avg-1.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        14 => {
            // sherpa-onnx-paraformer-zh-small-2024-03-09
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.paraformer = OfflineParaformerModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("paraformer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            config.rule_fsts = p("itn_zh_number.fst");
            Some(config)
        }

        15 => {
            // sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.sense_voice = OfflineSenseVoiceModelConfig {
                model: p("model.int8.onnx"),
                use_itn: true,
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        16 => {
            // sherpa-onnx-zipformer-ja-reazonspeech-2024-08-01
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder-epoch-99-avg-1.int8.onnx"),
                decoder: p("decoder-epoch-99-avg-1.onnx"),
                joiner: p("joiner-epoch-99-avg-1.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        17 => {
            // sherpa-onnx-zipformer-ru-2024-09-18
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        18 => {
            // sherpa-onnx-small-zipformer-ru-2024-09-18
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        19 => {
            // sherpa-onnx-nemo-ctc-giga-am-russian-2024-10-24
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        20 => {
            // sherpa-onnx-nemo-transducer-giga-am-russian-2024-10-24
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.onnx"),
                joiner: p("joiner.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("nemo_transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        21 => {
            // sherpa-onnx-moonshine-tiny-en-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                preprocessor: p("preprocess.onnx"),
                encoder: p("encode.int8.onnx"),
                uncached_decoder: p("uncached_decode.int8.onnx"),
                cached_decoder: p("cached_decode.int8.onnx"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        22 => {
            // sherpa-onnx-moonshine-base-en-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                preprocessor: p("preprocess.onnx"),
                encoder: p("encode.int8.onnx"),
                uncached_decoder: p("uncached_decode.int8.onnx"),
                cached_decoder: p("cached_decode.int8.onnx"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        23 => {
            // sherpa-onnx-zipformer-zh-en-2023-11-22
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder-epoch-34-avg-19.int8.onnx"),
                decoder: p("decoder-epoch-34-avg-19.onnx"),
                joiner: p("joiner-epoch-34-avg-19.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        24 => {
            // sherpa-onnx-fire-red-asr-large-zh_en-2025-02-16
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.fire_red_asr = OfflineFireRedAsrModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        25 => {
            // sherpa-onnx-dolphin-base-ctc-multi-lang-int8-2025-04-02
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.dolphin = OfflineDolphinModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        26 => {
            // sherpa-onnx-zipformer-vi-int8-2025-04-20
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder-epoch-12-avg-8.int8.onnx"),
                decoder: p("decoder-epoch-12-avg-8.onnx"),
                joiner: p("joiner-epoch-12-avg-8.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        27 => {
            // sherpa-onnx-nemo-ctc-giga-am-v2-russian-2025-04-19
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        28 => {
            // sherpa-onnx-nemo-transducer-giga-am-v2-russian-2025-04-19
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.onnx"),
                joiner: p("joiner.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("nemo_transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        29 => {
            // sherpa-onnx-zipformer-ru-int8-2025-04-20
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        30 => {
            // sherpa-onnx-nemo-parakeet-tdt-0.6b-v2-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.int8.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("nemo_transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        31 => {
            // sherpa-onnx-zipformer-ctc-zh-int8-2025-07-03
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.zipformer_ctc = OfflineZipformerCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        32 => {
            // sherpa-onnx-nemo-canary-180m-flash-en-es-de-fr-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.canary = OfflineCanaryModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.int8.onnx"),
                src_lang: Some("en".into()),
                tgt_lang: Some("en".into()),
                use_pnc: true,
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        33 => {
            // sherpa-onnx-nemo-parakeet_tdt_ctc_110m-en-36000-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        34 => {
            // sherpa-onnx-nemo-parakeet-tdt_ctc-0.6b-ja-35000-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        35 => {
            // sherpa-onnx-nemo-transducer-stt_pt_fastconformer_hybrid_large_pc-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.int8.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("nemo_transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        36 => {
            // sherpa-onnx-nemo-stt_pt_fastconformer_hybrid_large_pc-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        37 => {
            // sherpa-onnx-nemo-transducer-stt_de_fastconformer_hybrid_large_pc-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.int8.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("nemo_transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        38 => {
            // sherpa-onnx-nemo-stt_de_fastconformer_hybrid_large_pc-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.nemo_ctc = OfflineNemoEncDecCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        39 => {
            // sherpa-onnx-zipformer-ctc-small-zh-int8-2025-07-16
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.zipformer_ctc = OfflineZipformerCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        40 => {
            // sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.int8.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("nemo_transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        41 => {
            // sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2025-09-09
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.sense_voice = OfflineSenseVoiceModelConfig {
                model: p("model.int8.onnx"),
                use_itn: true,
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        42 => {
            // sherpa-onnx-wenetspeech-yue-u2pp-conformer-ctc-zh-en-cantonese-int8-2025-09-10
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.wenet_ctc = OfflineWenetCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        43 => {
            // sherpa-onnx-paraformer-zh-int8-2025-10-07
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.paraformer = OfflineParaformerModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("paraformer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        44 => {
            // sherpa-onnx-omnilingual-asr-1600-languages-300M-ctc-int8-2025-11-12
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.omnilingual = OfflineOmnilingualAsrCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        45 => {
            // sherpa-onnx-medasr-ctc-en-int8-2025-12-25
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.medasr = OfflineMedAsrCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        46 => {
            // sherpa-onnx-funasr-nano-int8-2025-12-30
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.funasr_nano = OfflineFunASRNanoModelConfig {
                encoder_adaptor: p("encoder_adaptor.int8.onnx"),
                llm: p("llm.int8.onnx"),
                embedding: p("embedding.int8.onnx"),
                tokenizer: p("Qwen3-0.6B"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 3;
            config.model_config.debug = true;
            Some(config)
        }

        47 => {
            // sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-int8-2026-02-03
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.wenet_ctc = OfflineWenetCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        48 => {
            // sherpa-onnx-wenetspeech-wu-u2pp-conformer-ctc-zh-2026-02-03
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.wenet_ctc = OfflineWenetCtcModelConfig {
                model: p("model.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        49 => {
            // sherpa-onnx-zipformer-vi-30M-int8-2026-02-09
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        50 => {
            // sherpa-onnx-fire-red-asr2-ctc-zh_en-int8-2026-02-25
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.fire_red_asr_ctc = OfflineFireRedAsrCtcModelConfig {
                model: p("model.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        51 => {
            // sherpa-onnx-moonshine-tiny-ko-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        52 => {
            // sherpa-onnx-moonshine-tiny-ja-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        53 => {
            // sherpa-onnx-moonshine-tiny-en-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        54 => {
            // sherpa-onnx-moonshine-base-zh-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        55 => {
            // sherpa-onnx-moonshine-base-vi-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        56 => {
            // sherpa-onnx-moonshine-base-uk-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        57 => {
            // sherpa-onnx-moonshine-base-ja-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        58 => {
            // sherpa-onnx-moonshine-base-es-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        59 => {
            // sherpa-onnx-moonshine-base-en-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        60 => {
            // sherpa-onnx-moonshine-base-ar-quantized-2026-02-27
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.moonshine = OfflineMoonshineModelConfig {
                encoder: p("encoder_model.ort"),
                merged_decoder: p("decoder_model_merged.ort"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        61 => {
            // sherpa-onnx-qwen3-asr-0.6B-int8-2026-03-25
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.qwen3_asr = OfflineQwen3ASRModelConfig {
                conv_frontend: p("conv_frontend.onnx"),
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.int8.onnx"),
                tokenizer: p("tokenizer"),
                ..Default::default()
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.num_threads = 3;
            config.model_config.debug = true;
            Some(config)
        }

        62 => {
            // sherpa-onnx-nemo-parakeet-unified-en-0.6b-int8-non-streaming
            let mut config = OfflineRecognizerConfig::default();
            config.model_config.transducer = OfflineTransducerModelConfig {
                encoder: p("encoder.int8.onnx"),
                decoder: p("decoder.int8.onnx"),
                joiner: p("joiner.int8.onnx"),
            };
            config.model_config.tokens = p("tokens.txt");
            config.model_config.model_type = Some("nemo_transducer".into());
            config.model_config.num_threads = 2;
            config.model_config.debug = true;
            Some(config)
        }

        _ => None,
    }
}