import com.k2fsa.sherpa.onnx.*;

public class NonStreamingTtsZipvoiceZhEn {
  public static void main(String[] args) {
    LibraryUtils.enableDebug();
    String textModel = "sherpa-onnx-zipvoice-distill-zh-en-emilia/text_encoder.onnx";
    String flowMatchingModel = "sherpa-onnx-zipvoice-distill-zh-en-emilia/fm_decoder.onnx";
    String vocoder = "sherpa-onnx-zipvoice-distill-zh-en-emilia/vocos_24khz.onnx";
    String pinyinDict = "sherpa-onnx-zipvoice-distill-zh-en-emilia/pinyin.raw";
    String tokens = "sherpa-onnx-zipvoice-distill-zh-en-emilia/tokens.txt";
    String dataDir = "sherpa-onnx-zipvoice-distill-zh-en-emilia/espeak-ng-data";
    String text =
        "中英文语音合成测试。This is generated by next generation Kaldi using Zipvoice."
            + " 你觉得中英文说的如何呢？";

    String promptWaveFilename =
        "sherpa-onnx-zipvoice-distill-zh-en-emilia/prompt.wav";

    WaveReader reader = new WaveReader(promptWaveFilename);

    OfflineTtsZipvoiceModelConfig zipvoiceModelConfig =
        OfflineTtsZipvoiceModelConfig.builder()
            .setTextModel(textModel)
            .setFlowMatchingModel(flowMatchingModel)
            .setVocoder(vocoder)
            .setPinyinDict(pinyinDict)
            .setTokens(tokens)
            .setDataDir(dataDir)
            .build();

    OfflineTtsModelConfig modelConfig =
        OfflineTtsModelConfig.builder()
            .setZipvoice(zipvoiceModelConfig)
            .setNumThreads(4)
            .setDebug(true)
            .build();

    OfflineTtsConfig config = OfflineTtsConfig.builder().setModel(modelConfig).build();
    OfflineTts tts = new OfflineTts(config);

    long start = System.currentTimeMillis();
    String prompt_text = "周日被我射熄火了，所以今天是周一。";
    GeneratedAudio audio = tts.generateWithPrompt(text, prompt_text, reader.getSamples(), reader.getSampleRate());
    long stop = System.currentTimeMillis();

    float timeElapsedSeconds = (stop - start) / 1000.0f;

    float audioDuration = audio.getSamples().length / (float) audio.getSampleRate();
    float real_time_factor = timeElapsedSeconds / audioDuration;

    String waveFilename = "tts-zipvoice-zh-en.wav";
    audio.save(waveFilename);
    System.out.printf("-- elapsed : %.3f seconds\n", timeElapsedSeconds);
    System.out.printf("-- audio duration: %.3f seconds\n", audioDuration);
    System.out.printf("-- real-time factor (RTF): %.3f\n", real_time_factor);
    System.out.printf("-- text: %s\n", text);
    System.out.printf("-- Saved to %s\n", waveFilename);

    tts.release();
  }
}
