/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.k2fsa.sherpaonnx;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
 
        assertNotNull("app test");
    }
}
