#!/usr/bin/env python3
# Generate offline-tts-supertonic-nfkd-table.h, the Unicode NFKD
# decomposition table used by the Supertonic TTS text frontend.
#
# The reference implementation of Supertonic
# (https://github.com/supertone-inc/supertonic, py/helper.py) applies
# unicodedata.normalize("NFKD", text) before mapping characters to ids
# with the unicode indexer. The indexer was built from NFKD text, so
# precomposed characters (e.g. Romanian ă/ș/ț, Czech č, Polish ą, ...)
# map to -1 and are silently dropped unless they are decomposed first.
#
# This script dumps Python's own NFKD data for the BMP into a compact
# C++ lookup table so the C++ runtime behaves like the reference
# implementation. Hangul syllables are excluded because they are
# decomposed algorithmically at runtime.
#
# Usage:  python3 generate_nfkd_table.py [output_header]

import sys
import unicodedata
from pathlib import Path

HANGUL_FIRST = 0xAC00
HANGUL_LAST = 0xD7A3


def collect_entries():
    entries = []
    for cp in range(0x10000):
        if HANGUL_FIRST <= cp <= HANGUL_LAST:
            continue
        ch = chr(cp)
        decomposed = unicodedata.normalize("NFKD", ch)
        if decomposed == ch:
            continue
        # Skip the rare mappings that leave the BMP; the runtime only
        # handles 16-bit values (the indexer covers U+0000..U+FFFF).
        if any(ord(c) > 0xFFFF for c in decomposed):
            continue
        entries.append((cp, [ord(c) for c in decomposed]))
    return entries


def format_array(values, per_line=9, indent="    "):
    lines = []
    for i in range(0, len(values), per_line):
        chunk = ", ".join(f"0x{v:04X}" for v in values[i : i + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def main():
    script_dir = Path(__file__).parent
    default_out = (
        script_dir.parent.parent
        / "sherpa-onnx"
        / "csrc"
        / "offline-tts-supertonic-nfkd-table.h"
    )
    out_path = Path(sys.argv[1]) if len(sys.argv) > 1 else default_out

    entries = collect_entries()
    entries.sort(key=lambda e: e[0])

    codepoints = [cp for cp, _ in entries]
    offsets = [0]
    pool = []
    for _, decomposed in entries:
        pool.extend(decomposed)
        offsets.append(len(pool))

    if len(pool) > 0xFFFF:
        print("Error: decomposition pool no longer fits in uint16_t offsets")
        return 1

    unicode_version = unicodedata.unidata_version

    header = f"""// sherpa-onnx/csrc/offline-tts-supertonic-nfkd-table.h
//
// Auto-generated by scripts/supertonic/generate_nfkd_table.py
// from Python's unicodedata (Unicode {unicode_version}). Do not edit by hand.
//
// NFKD decompositions for the Basic Multilingual Plane, excluding Hangul
// syllables (U+AC00..U+D7A3), which are decomposed algorithmically.
// This table is only meant to be included from
// offline-tts-supertonic-unicode-processor.cc.

#ifndef SHERPA_ONNX_CSRC_OFFLINE_TTS_SUPERTONIC_NFKD_TABLE_H_
#define SHERPA_ONNX_CSRC_OFFLINE_TTS_SUPERTONIC_NFKD_TABLE_H_

#include <cstdint>

namespace sherpa_onnx {{

constexpr int32_t kNfkdTableSize = {len(codepoints)};

// Codepoints that have an NFKD decomposition, sorted ascending.
static const uint16_t kNfkdCodepoints[kNfkdTableSize] = {{
{format_array(codepoints)}
}};

// kNfkdOffsets[i]..kNfkdOffsets[i+1] delimits the decomposition of
// kNfkdCodepoints[i] inside kNfkdPool.
static const uint16_t kNfkdOffsets[kNfkdTableSize + 1] = {{
{format_array(offsets)}
}};

static const uint16_t kNfkdPool[{len(pool)}] = {{
{format_array(pool)}
}};

}}  // namespace sherpa_onnx

#endif  // SHERPA_ONNX_CSRC_OFFLINE_TTS_SUPERTONIC_NFKD_TABLE_H_
"""

    out_path.write_text(header, encoding="utf-8")
    print(
        f"Wrote {len(codepoints)} entries ({len(pool)} pool values) -> {out_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
