name: tts
description: >
  This example shows how to implement text to speech, i.e., speech synthesis,
  using sherpa-onnx.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.13.4

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.8.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0
  path_provider: ^2.1.3
  path: ^1.9.0
  # sherpa_onnx: ^1.13.4
  sherpa_onnx:
    path: ../../flutter/sherpa_onnx
  sherpa_onnx_web:
    path: ../../flutter/sherpa_onnx_web
  url_launcher: 6.2.6
  url_launcher_linux: 3.1.0
  audioplayers: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/espeak-ng-data/
    - assets/espeak-ng-data/lang/
    - assets/espeak-ng-data/lang/aav/
    - assets/espeak-ng-data/lang/art/
    - assets/espeak-ng-data/lang/azc/
    - assets/espeak-ng-data/lang/bat/
    - assets/espeak-ng-data/lang/bnt/
    - assets/espeak-ng-data/lang/ccs/
    - assets/espeak-ng-data/lang/cel/
    - assets/espeak-ng-data/lang/cus/
    - assets/espeak-ng-data/lang/dra/
    - assets/espeak-ng-data/lang/esx/
    - assets/espeak-ng-data/lang/gmq/
    - assets/espeak-ng-data/lang/gmw/
    - assets/espeak-ng-data/lang/grk/
    - assets/espeak-ng-data/lang/inc/
    - assets/espeak-ng-data/lang/ine/
    - assets/espeak-ng-data/lang/ira/
    - assets/espeak-ng-data/lang/iro/
    - assets/espeak-ng-data/lang/itc/
    - assets/espeak-ng-data/lang/jpx/
    - assets/espeak-ng-data/lang/map/
    - assets/espeak-ng-data/lang/miz/
    - assets/espeak-ng-data/lang/myn/
    - assets/espeak-ng-data/lang/poz/
    - assets/espeak-ng-data/lang/roa/
    - assets/espeak-ng-data/lang/sai/
    - assets/espeak-ng-data/lang/sem/
    - assets/espeak-ng-data/lang/sit/
    - assets/espeak-ng-data/lang/tai/
    - assets/espeak-ng-data/lang/trk/
    - assets/espeak-ng-data/lang/urj/
    - assets/espeak-ng-data/lang/zle/
    - assets/espeak-ng-data/lang/zls/
    - assets/espeak-ng-data/lang/zlw/
    - assets/espeak-ng-data/voices/
    - assets/espeak-ng-data/voices/!v/
    - assets/kitten-nano-en-v0_1-fp16/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/aav/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/art/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/azc/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/bat/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/bnt/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/ccs/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/cel/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/cus/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/dra/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/esx/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/gmq/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/gmw/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/grk/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/inc/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/ine/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/ira/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/iro/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/itc/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/jpx/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/map/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/miz/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/myn/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/poz/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/roa/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/sai/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/sem/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/sit/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/tai/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/trk/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/urj/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/zle/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/zls/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/lang/zlw/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/voices/
    - assets/kitten-nano-en-v0_1-fp16/espeak-ng-data/voices/!v/
    - assets/kokoro-int8-en-v0_19/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/aav/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/art/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/azc/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/bat/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/bnt/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/ccs/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/cel/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/cus/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/dra/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/esx/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/gmq/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/gmw/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/grk/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/inc/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/ine/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/ira/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/iro/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/itc/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/jpx/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/map/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/miz/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/myn/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/poz/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/roa/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/sai/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/sem/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/sit/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/tai/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/trk/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/urj/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/zle/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/zls/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/lang/zlw/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/voices/
    - assets/kokoro-int8-en-v0_19/espeak-ng-data/voices/!v/
    - assets/kokoro-multi-lang-v1_0/
    - assets/kokoro-multi-lang-v1_0/dict/
    - assets/kokoro-multi-lang-v1_0/dict/pos_dict/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/aav/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/art/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/azc/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/bat/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/bnt/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/ccs/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/cel/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/cus/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/dra/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/esx/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/gmq/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/gmw/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/grk/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/inc/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/ine/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/ira/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/iro/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/itc/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/jpx/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/map/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/miz/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/myn/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/poz/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/roa/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/sai/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/sem/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/sit/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/tai/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/trk/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/urj/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/zle/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/zls/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/lang/zlw/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/voices/
    - assets/kokoro-multi-lang-v1_0/espeak-ng-data/voices/!v/
    - assets/matcha-icefall-en_US-ljspeech/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/aav/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/art/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/azc/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/bat/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/bnt/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/ccs/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/cel/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/cus/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/dra/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/esx/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/gmq/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/gmw/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/grk/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/inc/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/ine/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/ira/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/iro/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/itc/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/jpx/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/map/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/miz/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/myn/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/poz/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/roa/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/sai/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/sem/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/sit/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/tai/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/trk/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/urj/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/zle/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/zls/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/lang/zlw/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/voices/
    - assets/matcha-icefall-en_US-ljspeech/espeak-ng-data/voices/!v/
    - assets/matcha-icefall-zh-en/
    - assets/matcha-icefall-zh-en/espeak-ng-data/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/aav/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/art/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/azc/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/bat/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/bnt/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/ccs/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/cel/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/cus/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/dra/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/esx/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/gmq/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/gmw/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/grk/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/inc/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/ine/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/ira/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/iro/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/itc/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/jpx/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/map/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/miz/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/myn/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/poz/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/roa/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/sai/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/sem/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/sit/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/tai/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/trk/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/urj/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/zle/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/zls/
    - assets/matcha-icefall-zh-en/espeak-ng-data/lang/zlw/
    - assets/matcha-icefall-zh-en/espeak-ng-data/voices/
    - assets/matcha-icefall-zh-en/espeak-ng-data/voices/!v/
    - assets/sherpa-onnx-pocket-tts-int8-2026-01-26/
    - assets/sherpa-onnx-pocket-tts-int8-2026-01-26/test_wavs/
    - assets/vits-piper-en_US-amy-low/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/aav/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/art/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/azc/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/bat/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/bnt/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/ccs/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/cel/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/cus/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/dra/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/esx/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/gmq/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/gmw/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/grk/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/inc/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/ine/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/ira/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/iro/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/itc/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/jpx/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/map/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/miz/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/myn/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/poz/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/roa/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/sai/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/sem/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/sit/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/tai/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/trk/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/urj/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/zle/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/zls/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/lang/zlw/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/voices/
    - assets/vits-piper-en_US-amy-low/espeak-ng-data/voices/!v/
    - assets/vits-piper-en_US-libritts_r-medium/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/aav/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/art/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/azc/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/bat/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/bnt/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/ccs/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/cel/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/cus/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/dra/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/esx/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/gmq/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/gmw/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/grk/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/inc/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/ine/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/ira/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/iro/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/itc/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/jpx/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/map/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/miz/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/myn/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/poz/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/roa/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/sai/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/sem/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/sit/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/tai/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/trk/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/urj/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/zle/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/zls/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/lang/zlw/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/voices/
    - assets/vits-piper-en_US-libritts_r-medium/espeak-ng-data/voices/!v/
    - assets/vits-piper-zh_CN-xiao_ya-medium/
    - assets/vocos-16khz-univ.onnx
    - assets/vocos-22khz-univ.onnx
