#!/usr/bin/env python3
"""Generate test values with a direct DFT, independent of kaldi-native-fbank.

Equations follow current NVIDIA NeMo inference (dither disabled), pinned by
compare-reference.py. Historical NeMo 2.3.0 differs in padding/frame count.
Symmetric Hann, centered constant padding, Slaney mel filters, additive log
floor, and sample standard deviation over floor(samples / hop) valid frames.
Uses only the Python standard library. Run from any directory; writes stdout.
"""
import math

state = 42
samples = []
for _ in range(1281):
    state = (state * 1664525 + 1013904223) & 0xffffffff
    samples.append(((state >> 16) - 32768) / 327680.0)
emphasized = [samples[0]] + [samples[i] - .97 * samples[i-1] for i in range(1, len(samples))]


def hz_to_mel(hz):
    return hz / (200 / 3) if hz < 1000 else 15 + math.log(hz / 1000) / (math.log(6.4) / 27)


def mel_to_hz(mel):
    return mel * (200 / 3) if mel < 15 else 1000 * math.exp((mel - 15) * math.log(6.4) / 27)


edges = [mel_to_hz(i * hz_to_mel(8000) / 129) for i in range(130)]
features = []
for frame in range(8):
    windowed = []
    for j in range(400):
        i = frame * 160 + j - 200
        sample = emphasized[i] if 0 <= i < len(samples) else 0
        windowed.append(sample * (.5 - .5 * math.cos(2 * math.pi * j / 399)))
    power = []
    for k in range(257):
        real = sum(x * math.cos(2 * math.pi * k * j / 512) for j, x in enumerate(windowed))
        imag = sum(x * math.sin(2 * math.pi * k * j / 512) for j, x in enumerate(windowed))
        power.append(real * real + imag * imag)
    row = []
    for b in range(128):
        lo, mid, hi = edges[b:b+3]
        energy = sum(p * max(0, min((k * 16000 / 512 - lo) / (mid - lo),
                                   (hi - k * 16000 / 512) / (hi - mid))) * 2 / (hi - lo)
                     for k, p in enumerate(power))
        row.append(math.log(energy + 2**-24))
    features.append(row)
for b in range(128):
    mean = sum(f[b] for f in features) / 8
    std = math.sqrt(sum((f[b] - mean)**2 for f in features) / 7) + 1e-5
    for f in features:
        f[b] = (f[b] - mean) / std
# Sample across all frames, including low/high mel bins and the old cutoff.
print('// Generated by scripts/parakeet/generate-reference.py; do not edit.')
print('static const float kReference[8][8] = {')
for row in features:
    print('  {' + ', '.join(f'{row[b]:.8f}f' for b in [0, 1, 16, 32, 64, 96, 126, 127]) + '},')
print('};')
