name: hello_world
description: >
  A minimal Flutter example that displays sherpa-onnx version information.

publish_to: 'none'

version: 1.13.5

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  sherpa_onnx: ^1.13.5
  # sherpa_onnx:
  #   path: ../../flutter/sherpa_onnx

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
