name: build-xcframework

on:
  push:
    branches:
      - master
      - test-spm-2
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

  workflow_dispatch:

concurrency:
  group: build-xcframework-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_ios_xcframework:
    name: ios tts-${{ matrix.with_tts }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        with_tts: [ON, OFF]

    steps:
      - uses: actions/checkout@v4

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ios-tts-${{ matrix.with_tts }}

      - name: Build iOS shared
        # if: matrix.with_tts == 'ON'
        if: false
        shell: bash
        run: |
          export CMAKE_VERBOSE_MAKEFILE=ON
          ./build-ios-shared.sh

      - name: Build iOS
        if: matrix.with_tts == 'ON'
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ./build-ios.sh

      - name: Build iOS (No tts)
        if: matrix.with_tts == 'OFF'
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ./build-ios-no-tts.sh

      - name: Display artifacts
        if: matrix.with_tts == 'ON'
        shell: bash
        run: |
          ls -lh build-ios/*.xcframework.zip

      - name: Display artifacts
        if: matrix.with_tts == 'OFF'
        shell: bash
        run: |
          ls -lh build-ios-no-tts/*.xcframework.zip

      - name: Upload xcframework.zip
        if: matrix.with_tts == 'ON'
        uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-ios-xcframework
          path: ./build-ios/*.xcframework.zip

      - name: Upload xcframework.zip (no tts)
        if: matrix.with_tts == 'OFF'
        uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-ios-no-tts-xcframework
          path: ./build-ios-no-tts/*.xcframework.zip

      - name: Release xcframework
        if: github.repository_owner == 'k2-fsa' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: ./build-ios*/*.xcframework.zip

      - name: Release xcframework
        if: github.repository_owner == 'csukuangfj' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: ./build-ios*/*.xcframework.zip
          # repo_name: k2-fsa/sherpa-onnx
          # repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          # tag: v1.13.4

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            rm -rf huggingface
            export GIT_CLONE_PROTECTION_ACTIVE=false
            GIT_LFS_SKIP_SMUDGE=1 git clone https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/sherpa-onnx-libs huggingface

            cd huggingface

            cp -v ../build-ios*/*.xcframework.zip ./

            git status
            git lfs track "*.zip"

            git add .

            SHERPA_ONNX_VERSION=v$(grep "SHERPA_ONNX_VERSION" ../CMakeLists.txt | cut -d " " -f 2 | cut -d '"' -f 2)
            git commit -m "upload sherpa-onnx-${SHERPA_ONNX_VERSION} xcframework"

            git push https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/sherpa-onnx-libs main


  build_macos_xcframework:
    name: macos
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: macos

      - name: Build macOS
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          ./build-swift-macos.sh

      - name: Display artifacts
        shell: bash
        run: |
          ls -lh build-swift-macos/*.xcframework.zip

      - name: Upload xcframework.zip
        uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-macos-xcframework
          path: ./build-swift-macos/*.xcframework.zip

      - name: Release xcframework
        if: github.repository_owner == 'k2-fsa' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: ./build-swift-macos/*.xcframework.zip

      - name: Release xcframework
        if: github.repository_owner == 'csukuangfj' && github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          overwrite: true
          file: ./build-swift-macos/*.xcframework.zip
          # repo_name: k2-fsa/sherpa-onnx
          # repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          # tag: v1.13.4

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: (github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v3
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            rm -rf huggingface
            export GIT_CLONE_PROTECTION_ACTIVE=false
            GIT_LFS_SKIP_SMUDGE=1 git clone https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/sherpa-onnx-libs huggingface

            cd huggingface

            cp -v ../build-swift-macos/*.xcframework.zip ./

            git status
            git lfs track "*.zip"

            git add .

            SHERPA_ONNX_VERSION=v$(grep "SHERPA_ONNX_VERSION" ../CMakeLists.txt | cut -d " " -f 2 | cut -d '"' -f 2)
            git commit -m "upload sherpa-onnx-${SHERPA_ONNX_VERSION} macos xcframework"

            git push https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/sherpa-onnx-libs main
