name: nightly-wheel-arm

on:
  schedule:
    # minute (0-59)
    # hour (0-23)
    # day of the month (1-31)
    # month (1-12)
    # day of the week (0-6)
    # nightly build at 23:50 UTC time every day
    - cron: "50 23 * * *"

  workflow_dispatch:

concurrency:
  group: nightly-wheel-armv7l-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nightly-wheel-arm:
    if: github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa'
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-22.04-arm
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      - name: Run docker
        shell: bash
        run: |
            docker run --rm \
              --platform linux/arm/v7 \
              --volume ${{ github.workspace }}/:/home/runner/work/sherpa-onnx/sherpa-onnx \
              quay.io/pypa/manylinux_2_35_armv7l${{ matrix.python-version == '3.8' && ':2025.11.29-1' || '' }} \
            bash -c '
              uname -a

              python_version=${{ matrix.python-version }}

              cd /home/runner/work/sherpa-onnx/sherpa-onnx

              echo "--------------------"
              PY_GLOB="/opt/_internal/cpython-${python_version}*/bin"

              shopt -s nullglob
              matches=($PY_GLOB)
              shopt -u nullglob

              if [[ ${#matches[@]} -eq 0 ]]; then
                echo "No Python installation found for version $python_version"
                exit 1
              elif [[ ${#matches[@]} -gt 1 ]]; then
                echo "Multiple Python installations found for version $python_version:"
                printf "  %s\n" "${matches[@]}"
                echo "Using the first one: ${matches[0]}"
              fi

              PY_PATH="${matches[0]}"

              echo "$PY_PATH"
              export PATH="$PY_PATH:$PATH"
              which python3
              python3 --version

              python3 -m venv my

              source ./my/bin/activate

              git clone --depth 1 --branch v1.2.12 https://github.com/alsa-project/alsa-lib
              pushd alsa-lib
              ./gitcompile
              popd

              export LD_LIBRARY_PATH=$PWD/alsa-lib/src/.libs:$LD_LIBRARY_PATH

              pip install --no-deps sherpa-onnx
              python3 -c "import sherpa_onnx; print(sherpa_onnx.__file__, sherpa_onnx.__version__); print(dir(sherpa_onnx)); print(help(sherpa_onnx))"
            '
